name: Gary Wenneker's Blog
title: Gary Wenneker's Blog
description: Thoughts, stories and ideas
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
  - sitecore
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: gary@wenneker.org
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
